blueprint:
  name: Tuya TS0043 (_TZ3000_w8jwkczz) - 3 button remote (ZHA)
  description: >
    Works with Tuya TS0043 Zigbee scene switch (_TZ3000_w8jwkczz) under ZHA.
    Supports single press on buttons 1, 2, and 3.
  domain: automation
  input:
    device_ieee:
      name: Device IEEE
      description: "Find it in Settings → Devices → ZHA → your device → Info."
      selector:
        text:
    button_1_single:
      name: Button 1 — single press
      selector: {action: {}}
      default: []
    button_2_single:
      name: Button 2 — single press
      selector: {action: {}}
      default: []
    button_3_single:
      name: Button 3 — single press
      selector: {action: {}}
      default: []

trigger:
  - platform: event
    event_type: zha_event

variables:
  ieee: !input device_ieee

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {% set d = trigger.event.data %}
              {% set ieee_val = d.device_ieee
                               | default(d.ieee)
                               | default((d.device | default({})).get('ieee'))
                               | default('') %}
              {{ ieee_val == ieee }}
        sequence:
          - variables:
              ev: "{{ trigger.event.data }}"
              btn: "{{ ev.endpoint_id | default(0) }}"
              action_type: "{{ ev.command | default('') }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ btn == 1 and action_type == 'remote_button_short_press' }}"
                sequence: !input button_1_single
              - conditions:
                  - condition: template
                    value_template: "{{ btn == 2 and action_type == 'remote_button_short_press' }}"
                sequence: !input button_2_single
              - conditions:
                  - condition: template
                    value_template: "{{ btn == 3 and action_type == 'remote_button_short_press' }}"
                sequence: !input button_3_single
    default: []

mode: single
